general.vendor=Generic
general.name=ESP32-C6

apps.launcherAppId=Launcher

hardware.target=ESP32C6
hardware.flashSize=8MB
hardware.spiRam=false

dependencies.useDeprecatedHal=false

storage.userDataLocation=Internal
