general.vendor=Tulip
general.name=Tulip Creative Computer (4r11)

apps.launcherAppId=tactility.launcher

hardware.target=ESP32S3
hardware.flashSize=32MB
hardware.spiRam=true
hardware.spiRamMode=OCT
hardware.spiRamSpeed=120M
hardware.esptoolFlashFreq=120M
hardware.usbHostEnabled=true
hardware.bluetooth=true

storage.userDataLocation=Internal

touch.calibrationSupported=true
touch.calibrationRequired=false

display.size=7"
display.shape=rectangle
display.dpi=117

lvgl.colorDepth=16
lvgl.fontSize=20

sdkconfig.CONFIG_CODEC_DUMMY_SUPPORT=y
