general.vendor=M5Stack
general.name=CoreS3

apps.launcherAppId=tactility.launcher

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=QUAD
hardware.spiRamSpeed=120M
hardware.tinyUsbMsc=true
hardware.esptoolFlashFreq=120M
hardware.bluetooth=true

storage.userDataLocation=Internal

display.size=2"
display.shape=rectangle
display.dpi=200

lvgl.colorDepth=16
