project(tests)

set(DOCTESTINC ${PROJECT_SOURCE_DIR}/Doctest/Include)

enable_testing()
add_subdirectory(service-module)
add_subdirectory(TactilityFreeRtos)
add_subdirectory(TactilityKernel)
add_subdirectory(Tactility)
add_subdirectory(crypt-module)
add_subdirectory(app-module)

add_custom_target(build-tests)
add_dependencies(build-tests ServiceModuleTests)
add_dependencies(build-tests TactilityFreeRtosTests)
add_dependencies(build-tests TactilityTests)
add_dependencies(build-tests TactilityKernelTests)
add_dependencies(build-tests CryptModuleTests)
add_dependencies(build-tests AppModuleTests)
