general.vendor=LilyGO
general.name=T-Display
general.incubating=true

apps.launcherAppId=Launcher
apps.autoStartAppId=ApWebServer

hardware.target=ESP32
hardware.flashSize=16MB
hardware.spiRam=false
hardware.esptoolFlashFreq=80M

storage.userDataLocation=Internal

display.size=1.14"
display.shape=rectangle
display.dpi=242

lvgl.colorDepth=16
lvgl.uiDensity=compact
