[general]
vendor=CL-32
name=cl-32

[apps]
launcherAppId=Launcher

[hardware]
target=ESP32S3
flashSize=8MB
spiRam=true
spiRamMode=QUAD
spiRamSpeed=80M
esptoolFlashFreq=80M

[display]
size=2.9"
shape=rectangle
dpi=139

[lvgl]
colorDepth=8
theme=Mono

[sdkconfig]
# Fix error "PSRAM space not enough for the Flash instructions" on boot:
CONFIG_SPIRAM_FETCH_INSTRUCTIONS=n
CONFIG_SPIRAM_RODATA=n
CONFIG_SPIRAM_XIP_FROM_PSRAM=n
