#pragma once

#define TDECK_LCD_SPI_HOST SPI2_HOST
#define TDECK_LCD_PIN_CS GPIO_NUM_38
#define TDECK_LCD_PIN_DC GPIO_NUM_37 // RS
#define TDECK_LCD_HORIZONTAL_RESOLUTION 222
#define TDECK_LCD_VERTICAL_RESOLUTION 480
#define TDECK_LCD_SPI_TRANSFER_HEIGHT (TDECK_LCD_VERTICAL_RESOLUTION / 10)
