name: Build

inputs:
  os_name:
    description: A descriptive name for the operating system (e.g. linux, windows)
    required: true
  platform_name:
    description: A descriptive name for the target platform (e.g. amd64, aarch64, etc.)
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Wayland
      shell: bash
      run: |
        mkdir $XDG_RUNTIME_DIR
        chown $USER $XDG_RUNTIME_DIR
        chmod 0700 $XDG_RUNTIME_DIR
        sudo apt-get update
        sudo apt-get purge x11-*
        sudo apt-get install sway meson libwayland-dev
        echo $XDG_RUNTIME_DIR
      env:
        XDG_RUNTIME_DIR: /home/runner/work/tactility/xdg
        WLR_BACKENDS: headless
        WLR_LIBINPUT_NO_DEVICES: 1
        WAYLAND_DISPLAY: wayland-1
        GTK_USE_PORTAL: 0
    - name: "Checkout repo"
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: "Configure Project"
      uses: threeal/cmake-action@v1.3.0
    - name: 'Release'
      shell: bash
      run: Buildscripts/release-simulator.sh release/Simulator-${{ inputs.os_name }}-${{ inputs.platform_name }}
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: Simulator-${{ inputs.os_name }}-${{ inputs.platform_name }}
        path: release/Simulator-${{ inputs.os_name }}-${{ inputs.platform_name }}
        retention-days: 30
