#include <symbols/esp_http_client.h>
#include <esp_http_client.h>

const esp_elfsym esp_http_client_symbols[] = {
    ESP_ELFSYM_EXPORT(esp_http_client_init),
    ESP_ELFSYM_EXPORT(esp_http_client_perform),
    ESP_ELFSYM_EXPORT(esp_http_client_cancel_request),
    ESP_ELFSYM_EXPORT(esp_http_client_set_url),
    ESP_ELFSYM_EXPORT(esp_http_client_set_post_field),
    ESP_ELFSYM_EXPORT(esp_http_client_get_post_field),
    ESP_ELFSYM_EXPORT(esp_http_client_set_header),
    ESP_ELFSYM_EXPORT(esp_http_client_get_header),
    ESP_ELFSYM_EXPORT(esp_http_client_get_username),
    ESP_ELFSYM_EXPORT(esp_http_client_set_username),
    ESP_ELFSYM_EXPORT(esp_http_client_get_password),
    ESP_ELFSYM_EXPORT(esp_http_client_set_password),
    ESP_ELFSYM_EXPORT(esp_http_client_cancel_request),
    ESP_ELFSYM_EXPORT(esp_http_client_set_authtype),
    ESP_ELFSYM_EXPORT(esp_http_client_get_user_data),
    ESP_ELFSYM_EXPORT(esp_http_client_set_user_data),
    ESP_ELFSYM_EXPORT(esp_http_client_get_errno),
    ESP_ELFSYM_EXPORT(esp_http_client_get_and_clear_last_tls_error),
    ESP_ELFSYM_EXPORT(esp_http_client_set_method),
    ESP_ELFSYM_EXPORT(esp_http_client_set_timeout_ms),
    ESP_ELFSYM_EXPORT(esp_http_client_delete_header),
    ESP_ELFSYM_EXPORT(esp_http_client_delete_all_headers),
    ESP_ELFSYM_EXPORT(esp_http_client_open),
    ESP_ELFSYM_EXPORT(esp_http_client_write),
    ESP_ELFSYM_EXPORT(esp_http_client_fetch_headers),
    ESP_ELFSYM_EXPORT(esp_http_client_is_chunked_response),
    ESP_ELFSYM_EXPORT(esp_http_client_read),
    ESP_ELFSYM_EXPORT(esp_http_client_get_status_code),
    ESP_ELFSYM_EXPORT(esp_http_client_get_content_length),
    ESP_ELFSYM_EXPORT(esp_http_client_close),
    ESP_ELFSYM_EXPORT(esp_http_client_cleanup),
    ESP_ELFSYM_EXPORT(esp_http_client_get_transport_type),
    ESP_ELFSYM_EXPORT(esp_http_client_set_redirection),
    ESP_ELFSYM_EXPORT(esp_http_client_reset_redirect_counter),
    ESP_ELFSYM_EXPORT(esp_http_client_set_auth_data),
    ESP_ELFSYM_EXPORT(esp_http_client_add_auth),
    ESP_ELFSYM_EXPORT(esp_http_client_is_complete_data_received),
    ESP_ELFSYM_EXPORT(esp_http_client_read_response),
    ESP_ELFSYM_EXPORT(esp_http_client_flush_response),
    ESP_ELFSYM_EXPORT(esp_http_client_get_url),
    ESP_ELFSYM_EXPORT(esp_http_client_get_chunk_length),
};
