general.vendor=M5Stack
general.name=PaperS3
general.incubating=true

apps.launcherAppId=tactility.launcher

hardware.target=esp32s3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=OPI
hardware.spiRamSpeed=80M
hardware.esptoolFlashFreq=80M
hardware.tinyUsbMsc=true
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=4.7"
display.shape=rectangle
display.dpi=235

lvgl.colorDepth=8
lvgl.fontSize=24
lvgl.theme=Mono

sdkconfig.CONFIG_EPD_DISPLAY_TYPE_ED047TC2=y
sdkconfig.CONFIG_LV_THEME_DEFAULT_TRANSITION_TIME=0