#pragma once

#define YELLOW_LCD_SPI_HOST SPI2_HOST
#define YELLOW_LCD_PIN_CS GPIO_NUM_15
#define YELLOW_TOUCH_PIN_CS GPIO_NUM_25  // Updated from 33
#define YELLOW_LCD_PIN_DC GPIO_NUM_2
#define YELLOW_LCD_HORIZONTAL_RESOLUTION 240
#define YELLOW_LCD_VERTICAL_RESOLUTION 320
#define YELLOW_LCD_SPI_TRANSFER_HEIGHT (YELLOW_LCD_VERTICAL_RESOLUTION / 10)  // 32
