general.vendor=Waveshare
general.name=ESP32 S3 GEEK
general.incubating=true

apps.launcherAppId=Launcher
apps.autoStartAppId=ApWebServer

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=QUAD
hardware.spiRamSpeed=120M
hardware.tinyUsb=true
hardware.esptoolFlashFreq=120M
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=1.14"
display.shape=rectangle
display.dpi=143

lvgl.colorDepth=16
lvgl.uiDensity=compact

# Fix error "PSRAM space not enough for the Flash instructions" on boot:
sdkconfig.CONFIG_SPIRAM_FETCH_INSTRUCTIONS=n
sdkconfig.CONFIG_SPIRAM_RODATA=n
sdkconfig.CONFIG_SPIRAM_XIP_FROM_PSRAM=n
