general.vendor=Waveshare
general.name=ESP32 S3 GEEK
general.incubating=true

apps.launcherAppId=tactility.launcher
apps.autoStartAppId=tactility.apwebserver

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=QUAD
hardware.spiRamSpeed=120M
hardware.spiRamXipDisabled=true
hardware.tinyUsbMsc=true
hardware.esptoolFlashFreq=120M
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=1.14"
display.shape=rectangle
display.dpi=143

lvgl.colorDepth=16
lvgl.uiDensity=compact
