general.vendor=WaveShare
general.name=S3 Touch LCD 1.28"
general.incubating=true

apps.launcherAppId=tactility.launcher
apps.autoStartAppId=tactility.apwebserver

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=QUAD
hardware.spiRamSpeed=120M
hardware.spiRamXipDisabled=true
hardware.tinyUsbMsc=true
hardware.esptoolFlashFreq=120M
hardware.bluetooth=true

storage.userDataLocation=Internal

display.size=1.28"
display.shape=circle
display.dpi=265

lvgl.colorDepth=16
lvgl.uiDensity=compact
