general.vendor=M5Stack
general.name=StickC Plus2

apps.launcherAppId=Launcher

hardware.target=ESP32
hardware.flashSize=8MB
hardware.spiRam=true
hardware.spiRamMode=QUAD
hardware.spiRamSpeed=80M
hardware.esptoolFlashFreq=80M

storage.userDataLocation=Internal

display.size=1.14"
display.shape=rectangle
display.dpi=242

lvgl.colorDepth=16
lvgl.uiDensity=compact
