name: Build

inputs:
  board_id:
    description: The sdkconfig file to build
    required: true
  arch:
    description: The ESP32 SOC variant
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: 'Board select'
      shell: bash
      run: cp sdkconfig.board.${{ inputs.board_id }} sdkconfig

    - name: 'Install ccache'
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y ccache

    - name: 'Cache ccache'
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ hashFiles('**/*.c') }}-${{ hashFiles('**/*.h') }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: 'Enable ccache'
      shell: bash
      run: |
        echo "IDF_CCACHE_ENABLE=1" >> $GITHUB_ENV
        echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV
        echo "PATH=/usr/lib/ccache:$PATH" >> $GITHUB_ENV

    - name: 'Build'
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.5
        target: ${{ inputs.arch }}
        path: './'

    - name: 'Release'
      shell: bash
      run: Buildscripts/release.sh ${{ inputs.board_id }}

    - name: 'Upload Artifact: Release'
      uses: actions/upload-artifact@v4
      with:
        name: Tactility-${{ inputs.board_id }}
        path: release/Tactility-${{ inputs.board_id }}
        retention-days: 30

    - name: 'Upload Artifact: Release symbols'
      uses: actions/upload-artifact@v4
      with:
        name: Tactility-${{ inputs.board_id }}-symbols
        path: release/Tactility-${{ inputs.board_id }}-symbols
        retention-days: 30
