general.vendor=Guition
general.name=JC2432W328C

apps.launcherAppId=Launcher

hardware.target=ESP32
hardware.flashSize=4MB
hardware.spiRam=false

dependencies.useDeprecatedHal=false

storage.userDataLocation=SD

display.size=2.8"
display.shape=rectangle
display.dpi=143

lvgl.colorDepth=16
