general.vendor=WaveShare
general.name=S3 Touch LCD 1.47"
general.incubating=true

apps.launcherAppId=tactility.launcher

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=OCT
hardware.spiRamSpeed=120M
hardware.tinyUsbMsc=true
hardware.esptoolFlashFreq=120M
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=1.47"
display.shape=rectangle
display.dpi=247

lvgl.colorDepth=16
lvgl.uiDensity=compact
