general.vendor=unPhone
general.name=unPhone

apps.launcherAppId=Launcher

hardware.target=ESP32S3
hardware.flashSize=8MB
hardware.spiRam=true
hardware.spiRamMode=OCT
hardware.spiRamSpeed=80M
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=3.5"
display.shape=rectangle
display.dpi=165

touch.calibrationSupported=true
touch.calibrationRequired=true

cdn.warningMessage=Put the device into bootloader mode by pressing the center nav button and reset for 2-3 seconds, then release reset, then release the nav button.<br/>After flashing is finished, press the reset button to reboot.

lvgl.colorDepth=24
