name: "Generate boards"
description: "Run Buildscripts/generate-boards.py, print results."

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Make generator executable
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -euo pipefail
        if [ -f Buildscripts/generate-boards.py ]; then
          chmod +x Buildscripts/generate-boards.py
        fi

    - name: Run generator
      id: run-generator
      shell: bash
      run: |
        set -euo pipefail
        if [ -f Buildscripts/generate-boards.py ]; then
          python3 Buildscripts/generate-boards.py --list-changed
          echo "ran-generator=true" >> $GITHUB_OUTPUT
        else
          echo "ran-generator=false" >> $GITHUB_OUTPUT
        fi
