name: "Generate boards"
description: "Run Buildscripts/generate-boards.py, print results."

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Make generator executable
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -euo pipefail
        if [ -f Buildscripts/generate_boards.py ]; then
          chmod +x Buildscripts/generate_boards.py
        fi

    - name: Run generator
      id: run-generator
      shell: bash
      run: |
        set -euo pipefail
        if [ -f Buildscripts/generate_boards.py ]; then
          python3 Buildscripts/generate_boards.py --list-changed
          echo "ran-generator=true" >> $GITHUB_OUTPUT
        else
          echo "ran-generator=false" >> $GITHUB_OUTPUT
        fi

    - name: Check generated files are committed
      shell: bash
      run: |
        set -euo pipefail

        # Files that are generated by generate_boards.py
        GENERATED_FILES=(
          "Firmware/Kconfig"
          "Firmware/Source/Boards.h"
          "Buildscripts/board.cmake"
          "Buildscripts/build-and-release-all.sh"
        )

        # Path to generator (treat changes to this specially)
        GENERATOR="Buildscripts/generate_boards.py"

        # Collect changed files (staged/unstaged/untracked)
        mapfile -t CHANGED < <(git --no-pager status --porcelain --untracked-files=all | awk '{print $2}')

        if [ "${#CHANGED[@]}" -eq 0 ]; then
          echo "No changes in working tree."
          exit 0
        fi

        changed_generated=false
        changed_generator=false
        other_changes=()

        for f in "${CHANGED[@]}"; do
          if [ "$f" = "$GENERATOR" ]; then
            changed_generator=true
            continue
          fi

          found=false
          for gf in "${GENERATED_FILES[@]}"; do
            if [ "$f" = "$gf" ]; then
              changed_generated=true
              found=true
              break
            fi
          done

          if [ "$found" = "false" ]; then
            other_changes+=("$f")
          fi
        done

        if [ "${#other_changes[@]}" -gt 0 ]; then
          echo "ERROR: Unexpected changed files (not generator or generated outputs):"
          for x in "${other_changes[@]}"; do
            echo "  $x"
          done
          echo
          echo "If these are unrelated changes, commit or revert them. If you intended them, ensure they're included in this PR."
          exit 1
        fi

        if [ "$changed_generated" = "true" ]; then
          echo "ERROR: Generated files are out-of-date. Run:"
          echo "  python3 Buildscripts/generate_boards.py"
          echo "then git add/commit the generated files and re-run the CI."
          echo
          echo "Changed generated files:"
          for gf in "${GENERATED_FILES[@]}"; do
            if git --no-pager status --porcelain --untracked-files=all | awk '{print $2}' | grep -xq "$gf"; then
              echo "  $gf"
            fi
          done
          exit 1
        fi

        if [ "$changed_generator" = "true" ]; then
          echo "ERROR: The generator script ($GENERATOR) changed but the generated outputs were not updated."
          echo "You likely modified the generator; please run:"
          echo "  python3 Buildscripts/generate_boards.py"
          echo "and commit any updated generated files (e.g. Firmware/Kconfig, Firmware/Source/Boards.h, Buildscripts/board.cmake, ...)."
          exit 1
        fi

        # if we get here, there are no generator/generated-file changes (shouldn't happen)
        echo "No generated-file or generator changes detected; nothing to do."
        exit 0
