// SPDX-License-Identifier: Apache-2.0
#include <c_symbols/module.h>

#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <ctype.h>
#include <locale.h>

extern "C" {

static const ModuleSymbol c_symbols_module_symbols[] = {
    // stdlib.h
    DEFINE_MODULE_SYMBOL(malloc),
    DEFINE_MODULE_SYMBOL(calloc),
    DEFINE_MODULE_SYMBOL(realloc),
    DEFINE_MODULE_SYMBOL(free),
    DEFINE_MODULE_SYMBOL(rand),
    DEFINE_MODULE_SYMBOL(srand),
    DEFINE_MODULE_SYMBOL(atof),
    DEFINE_MODULE_SYMBOL(atoi),
    DEFINE_MODULE_SYMBOL(atol),
    DEFINE_MODULE_SYMBOL(system),
    DEFINE_MODULE_SYMBOL(getenv),
    DEFINE_MODULE_SYMBOL(qsort),
    // time.h
    DEFINE_MODULE_SYMBOL(strftime),
    DEFINE_MODULE_SYMBOL(time),
    DEFINE_MODULE_SYMBOL(difftime),
    DEFINE_MODULE_SYMBOL(localtime),
    DEFINE_MODULE_SYMBOL(mktime),
    // math.h
    DEFINE_MODULE_SYMBOL(acos),
    DEFINE_MODULE_SYMBOL(acoshf),
    DEFINE_MODULE_SYMBOL(acosf),
    DEFINE_MODULE_SYMBOL(asin),
    DEFINE_MODULE_SYMBOL(asinhf),
    DEFINE_MODULE_SYMBOL(asinf),
    DEFINE_MODULE_SYMBOL(atan),
    DEFINE_MODULE_SYMBOL(atanhf),
    DEFINE_MODULE_SYMBOL(atanf),
    DEFINE_MODULE_SYMBOL(atan2),
    DEFINE_MODULE_SYMBOL(atan2f),
    DEFINE_MODULE_SYMBOL(cos),
    DEFINE_MODULE_SYMBOL(coshf),
    DEFINE_MODULE_SYMBOL(cosf),
    DEFINE_MODULE_SYMBOL(sin),
    DEFINE_MODULE_SYMBOL(sinh),
    DEFINE_MODULE_SYMBOL(sinhf),
    DEFINE_MODULE_SYMBOL(sinf),
    DEFINE_MODULE_SYMBOL(tan),
    DEFINE_MODULE_SYMBOL(tanhf),
    DEFINE_MODULE_SYMBOL(tanf),
    DEFINE_MODULE_SYMBOL(exp),
    DEFINE_MODULE_SYMBOL(expf),
    DEFINE_MODULE_SYMBOL(ldexp),
    DEFINE_MODULE_SYMBOL(ldexpf),
    DEFINE_MODULE_SYMBOL(log),
    DEFINE_MODULE_SYMBOL(logf),
    DEFINE_MODULE_SYMBOL(log10),
    DEFINE_MODULE_SYMBOL(log10f),
    DEFINE_MODULE_SYMBOL(pow),
    DEFINE_MODULE_SYMBOL(powf),
    DEFINE_MODULE_SYMBOL(sqrt),
    DEFINE_MODULE_SYMBOL(sqrtf),
    DEFINE_MODULE_SYMBOL(fmod),
    DEFINE_MODULE_SYMBOL(fmodf),
    DEFINE_MODULE_SYMBOL(frexp),
    DEFINE_MODULE_SYMBOL(frexpf),
    DEFINE_MODULE_SYMBOL(modf),
    DEFINE_MODULE_SYMBOL(modff),
    DEFINE_MODULE_SYMBOL(ceil),
    DEFINE_MODULE_SYMBOL(ceilf),
    DEFINE_MODULE_SYMBOL(fabs),
    DEFINE_MODULE_SYMBOL(fabsf),
    DEFINE_MODULE_SYMBOL(floor),
    DEFINE_MODULE_SYMBOL(floorf),
    DEFINE_MODULE_SYMBOL(fmax),
    DEFINE_MODULE_SYMBOL(fmaxf),
    DEFINE_MODULE_SYMBOL(fmin),
    DEFINE_MODULE_SYMBOL(fminf),
    DEFINE_MODULE_SYMBOL(round),
    DEFINE_MODULE_SYMBOL(roundf),
    // cassert / cstdio
    DEFINE_MODULE_SYMBOL(abort),
    DEFINE_MODULE_SYMBOL(fclose),
    DEFINE_MODULE_SYMBOL(feof),
    DEFINE_MODULE_SYMBOL(ferror),
    DEFINE_MODULE_SYMBOL(fflush),
    DEFINE_MODULE_SYMBOL(fgetc),
    DEFINE_MODULE_SYMBOL(fgetpos),
    DEFINE_MODULE_SYMBOL(fgets),
    DEFINE_MODULE_SYMBOL(fopen),
    DEFINE_MODULE_SYMBOL(freopen),
    DEFINE_MODULE_SYMBOL(setvbuf),
    DEFINE_MODULE_SYMBOL(fputc),
    DEFINE_MODULE_SYMBOL(fputs),
    DEFINE_MODULE_SYMBOL(fprintf),
    DEFINE_MODULE_SYMBOL(fread),
    DEFINE_MODULE_SYMBOL(fseek),
    DEFINE_MODULE_SYMBOL(fsetpos),
    DEFINE_MODULE_SYMBOL(fscanf),
    DEFINE_MODULE_SYMBOL(ftell),
    DEFINE_MODULE_SYMBOL(fwrite),
    DEFINE_MODULE_SYMBOL(getc),
    DEFINE_MODULE_SYMBOL(putc),
    DEFINE_MODULE_SYMBOL(putchar),
    DEFINE_MODULE_SYMBOL(puts),
    DEFINE_MODULE_SYMBOL(printf),
    DEFINE_MODULE_SYMBOL(sscanf),
    DEFINE_MODULE_SYMBOL(snprintf),
    DEFINE_MODULE_SYMBOL(sprintf),
    DEFINE_MODULE_SYMBOL(vsprintf),
    DEFINE_MODULE_SYMBOL(vsnprintf),
    DEFINE_MODULE_SYMBOL(vfprintf),
    DEFINE_MODULE_SYMBOL(rename),
    DEFINE_MODULE_SYMBOL(rewind),
    DEFINE_MODULE_SYMBOL(remove),
    // cstring
    DEFINE_MODULE_SYMBOL(strlen),
    DEFINE_MODULE_SYMBOL(strcmp),
    DEFINE_MODULE_SYMBOL(strncmp),
    DEFINE_MODULE_SYMBOL(strncpy),
    DEFINE_MODULE_SYMBOL(strcpy),
    DEFINE_MODULE_SYMBOL(strcat),
    // <cstring>'s C++ overloads (const/non-const char* variants of the same C symbol) make a bare
    // `&strchr` ambiguous - disambiguate with an explicit function-pointer cast.
    { "strchr", (void*)static_cast<const char* (*)(const char*, int)>(&strchr) },
    { "strstr", (void*)static_cast<const char* (*)(const char*, const char*)>(&strstr) },
    DEFINE_MODULE_SYMBOL(strerror),
    DEFINE_MODULE_SYMBOL(strtod),
    { "strrchr", (void*)static_cast<const char* (*)(const char*, int)>(&strrchr) },
    DEFINE_MODULE_SYMBOL(strtol),
    DEFINE_MODULE_SYMBOL(strtoul),
    DEFINE_MODULE_SYMBOL(strcspn),
    DEFINE_MODULE_SYMBOL(strncat),
    { "strpbrk", (void*)static_cast<const char* (*)(const char*, const char*)>(&strpbrk) },
    DEFINE_MODULE_SYMBOL(strspn),
    DEFINE_MODULE_SYMBOL(strcoll),
    DEFINE_MODULE_SYMBOL(memset),
    DEFINE_MODULE_SYMBOL(memcpy),
    DEFINE_MODULE_SYMBOL(memcmp),
    { "memchr", (void*)static_cast<const void* (*)(const void*, int, size_t)>(&memchr) },
    DEFINE_MODULE_SYMBOL(memmove),
    // ctype.h
    DEFINE_MODULE_SYMBOL(isalnum),
    DEFINE_MODULE_SYMBOL(isalpha),
    DEFINE_MODULE_SYMBOL(iscntrl),
    DEFINE_MODULE_SYMBOL(isdigit),
    DEFINE_MODULE_SYMBOL(isgraph),
    DEFINE_MODULE_SYMBOL(islower),
    DEFINE_MODULE_SYMBOL(isprint),
    DEFINE_MODULE_SYMBOL(ispunct),
    DEFINE_MODULE_SYMBOL(isspace),
    DEFINE_MODULE_SYMBOL(isupper),
    DEFINE_MODULE_SYMBOL(isxdigit),
    DEFINE_MODULE_SYMBOL(tolower),
    DEFINE_MODULE_SYMBOL(toupper),
    // locale.h
    DEFINE_MODULE_SYMBOL(localeconv),
    MODULE_SYMBOL_TERMINATOR
};

Module c_symbols_module = {
    .name = "c-symbols",
    .symbols = c_symbols_module_symbols
};

}
