general.vendor=Wireless Tag
general.name=WT32 SC01 Plus

apps.launcherAppId=Launcher

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=QUAD
hardware.spiRamSpeed=80M
hardware.tinyUsb=true
hardware.esptoolFlashFreq=80M
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=3.5"
display.shape=rectangle
display.dpi=165

lvgl.colorDepth=16
