general.vendor=Generic
general.name=ESP32-P4

apps.launcherAppId=Launcher

hardware.target=ESP32P4
hardware.flashSize=8MB
hardware.spiRam=false

dependencies.useDeprecatedHal=false

storage.userDataLocation=Internal
