[general]
vendor=LilyGO
name=T-Dongle S3
incubating=true

[apps]
launcherAppId=Launcher
autoStartAppId=ApWebServer

[hardware]
target=ESP32S3
flashSize=16MB
spiRam=false
tinyUsb=true
esptoolFlashFreq=120M
bluetooth=true

[display]
size=0.96"
shape=rectangle
dpi=186

[lvgl]
colorDepth=16
uiDensity=compact
fontSize=10
