general.vendor=LilyGO
general.name=T-Dongle S3
general.incubating=true

apps.launcherAppId=Launcher
apps.autoStartAppId=ApWebServer

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=false
hardware.tinyUsb=true
hardware.esptoolFlashFreq=120M
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=0.96"
display.shape=rectangle
display.dpi=186

lvgl.colorDepth=16
lvgl.uiDensity=compact
lvgl.fontSize=10
