name: Build
on:
  workflow_call:
    inputs:
      board-name:
        description: The name of the board
        required: true
      version:
        description: The name of the board
        required: true
      sdkconfig:
        description: The sdkconfig file to build
        required: true
      arch:
        description: The ESP32 SOC variant
        required: true

jobs:
  Build-Board:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 'Board select'
        shell: bash
        run: cp ${{ on.workflow_call.inputs.sdkconfig }} sdkconfig
      - name: build
        uses: espressif/esp-idf-ci-action@main
        with:
          esp_idf_version: v5.3.1
          target: ${{ on.workflow_call.inputs.arch }}
          path: './'
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: tactility-${{ on.workflow_call.inputs.board-name }}-${{ on.workflow_call.inputs.version }}
          path: build/Tactility.bin
          retention-days: 5
