general.vendor=Guition
general.name=JC3248W535C

apps.launcherAppId=Launcher

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=OCT
hardware.spiRamSpeed=120M
hardware.tinyUsb=true
hardware.esptoolFlashFreq=120M
hardware.bluetooth=true

dependencies.useDeprecatedHal=false

storage.userDataLocation=SD

display.size=3.5"
display.shape=rectangle
display.dpi=165

lvgl.colorDepth=16

sdkconfig.CONFIG_CODEC_DUMMY_SUPPORT=y
