#pragma once

#include "driver/spi_common.h"
#include "driver/gpio.h"

// SD Card
#define CORES3_SDCARD_SPI_HOST SPI2_HOST
#define CORES3_SDCARD_PIN_CS GPIO_NUM_4
#define CORES3_SDCARD_SPI_FREQUENCY 800000U
#define CORES3_SDCARD_FORMAT_ON_MOUNT_FAILED false
#define CORES3_SDCARD_MAX_OPEN_FILES 4
#define CORES3_SDCARD_ALLOC_UNIT_SIZE (16 * 1024)
#define CORES3_SDCARD_STATUS_CHECK_ENABLED false
