general.vendor=Elecrow
general.name=CrowPanel Advance 3.5"

apps.launcherAppId=tactility.launcher

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=OCT
hardware.spiRamSpeed=120M
hardware.tinyUsbMsc=true
hardware.esptoolFlashFreq=120M
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=3.5"
display.shape=rectangle
display.dpi=165

cdn.warningMessage=This device has display driver and memory issues. App Hub doesn't work.

lvgl.colorDepth=16
