general.vendor=BigTreeTech
general.name=Panda Touch,K Touch

apps.launcherAppId=Launcher

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=OCT
hardware.spiRamSpeed=120M
hardware.esptoolFlashFreq=120M
hardware.bluetooth=true
hardware.usbHostEnabled=true

storage.userDataLocation=Internal

display.size=5"
display.shape=rectangle
display.dpi=187

lvgl.colorDepth=16
lvgl.fontSize=18
