general.vendor=CL-32
general.name=CL-32

apps.launcherAppId=Launcher

hardware.target=ESP32S3
hardware.flashSize=8MB
hardware.spiRam=true
hardware.spiRamMode=QUAD
hardware.spiRamSpeed=80M
hardware.esptoolFlashFreq=80M
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=2.9"
display.shape=rectangle
display.dpi=139

lvgl.colorDepth=8
lvgl.theme=Mono

# Fix error "PSRAM space not enough for the Flash instructions" on boot:
sdkconfig.CONFIG_SPIRAM_FETCH_INSTRUCTIONS=n
sdkconfig.CONFIG_SPIRAM_RODATA=n
sdkconfig.CONFIG_SPIRAM_XIP_FROM_PSRAM=n
