general.vendor=CL-32
general.name=CL-32

apps.launcherAppId=tactility.launcher

hardware.target=ESP32S3
hardware.flashSize=8MB
hardware.spiRam=true
hardware.spiRamMode=QUAD
hardware.spiRamSpeed=80M
hardware.spiRamXipDisabled=true
hardware.esptoolFlashFreq=80M
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=2.9"
display.shape=rectangle
display.dpi=139

lvgl.colorDepth=8
lvgl.theme=Mono
