if (NOT WIN32)
    string(ASCII 27 Esc)
    set(ColorReset "${Esc}[m")
    set(Cyan        "${Esc}[36m")
    set(Grey        "${Esc}[37m")
    set(LightPurple "${Esc}[1;35m")
    set(White       "${Esc}[1;37m")
else ()
    set(ColorReset "")
    set(Cyan        "")
    set(Grey        "")
    set(LightPurple "")
    set(White       "")
endif ()
