general.vendor=Heltec
general.name=WiFi LoRa 32 v3
general.incubating=true

apps.launcherAppId=Launcher
apps.autoStartAppId=ApWebServer

hardware.target=ESP32S3
hardware.flashSize=8MB
hardware.spiRam=false
hardware.tinyUsb=true
hardware.esptoolFlashFreq=120M
hardware.bluetooth=true

dependencies.useDeprecatedHal=false

storage.userDataLocation=Internal

display.size=0.96"
display.shape=rectangle
display.dpi=149

cdn.infoMessage=Due to the small size of the screen, the icons don't render properly.

lvgl.theme=Mono
lvgl.colorDepth=16
lvgl.uiScale=70
lvgl.uiDensity=compact
