name: Build

inputs:
  board_id:
    description: The sdkconfig file to build
    required: true
  arch:
    description: The ESP32 SOC variant
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: 'Board select'
      shell: bash
      run: cp sdkconfig.board.${{ inputs.board_id }} sdkconfig

    # Install ccache
    - name: 'Install ccache'
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y ccache

    # Cache per-board ccache
    - name: 'Cache ccache'
      uses: actions/cache@v3
      with:
        path: ~/.ccache-${{ inputs.board_id }}
        key: ${{ runner.os }}-ccache-${{ inputs.board_id }}-${{ hashFiles('**/*.c') }}-${{ hashFiles('**/*.h') }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ inputs.board_id }}-

    # Enable ccache for ESP-IDF build
    - name: 'Enable ccache'
      shell: bash
      run: |
        export CCACHE_DIR=$HOME/.ccache-${{ inputs.board_id }}
        echo "IDF_CCACHE_ENABLE=1" >> $GITHUB_ENV
        echo "CCACHE_DIR=$CCACHE_DIR" >> $GITHUB_ENV
        echo "PATH=/usr/lib/ccache:$PATH" >> $GITHUB_ENV

    # ESP-IDF build
    - name: 'Build'
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.5
        target: ${{ inputs.arch }}
        path: './'

    # Release
    - name: 'Release'
      shell: bash
      env:
        ESP_IDF_VERSION: '5.5'
      run: Buildscripts/release-sdk.sh release/TactilitySDK

    # Upload artifact
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: TactilitySDK-${{ inputs.arch }}
        path: release/TactilitySDK
        retention-days: 30
