general.vendor=Xteink
general.name=X4

apps.launcherAppId=Launcher

hardware.target=ESP32C3
hardware.flashSize=16MB
hardware.flashMode=DIO
hardware.spiRam=false
hardware.tinyUsb=true
hardware.wifi=true
hardware.bluetooth=true

storage.userDataLocation=SD

sdkconfig.CONFIG_BOOTLOADER_LOG_LEVEL_INFO=y
