general.vendor=Xteink
general.name=X4

apps.launcherAppId=Launcher

hardware.target=ESP32C3
hardware.flashSize=16MB
hardware.flashMode=DIO
hardware.spiRam=false
hardware.tinyUsb=true
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=4.26"
display.shape=rectangle
display.dpi=230

lvgl.colorDepth=8
lvgl.theme=Mono

sdkconfig.CONFIG_BOOTLOADER_LOG_LEVEL_INFO=y
