general.vendor=WaveShare
general.name=S3 LCD 1.3"
general.incubating=true

apps.launcherAppId=Launcher
apps.autoStartAppId=ApWebServer

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=OCT
hardware.spiRamSpeed=120M
hardware.tinyUsb=true
hardware.esptoolFlashFreq=120M
hardware.bluetooth=true

dependencies.useDeprecatedHal=false

storage.userDataLocation=SD

display.size=1.3"
display.shape=rectangle
display.dpi=261

lvgl.colorDepth=16
lvgl.uiDensity=compact
