@startuml
[*] --> on_create : app is started
on_create --> on_show : app becomes visible
on_show --> on_hide : app is no longer visible
on_hide --> on_destroy : app is being closed
on_destroy --> [*]
skinparam ranksep 25
skinparam padding 2
@enduml