@startuml
skinparam componentStyle uml1

[tactility] as t
note right of t : to build and use graphical apps
[tactility-headless] as theadless
note right of theadless : to build and use background services
[tactility-core] as tcore
note right of tcore : defines, data types, logging, async, etc.

package "Applications" {
  [app-sim] as appsim
  [app-esp] as appesp
}

note right of appesp : app-esp depends on the board \n projects for configuration

[t] ..> [theadless]
[theadless] ..> [tcore]
[appsim] ..> [t]
[appesp] ..> [t]

@enduml