name: Bundle All

runs:
  using: 'composite'
  steps:
    - name: 'Download artifacts'
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: 'all-artifacts'
        path: artifacts/
        retention-days: 3
