// SPDX-License-Identifier: Apache-2.0
#include <tactility/lvgl_module.h>
#include <tactility/lvgl_fonts.h>

#include <lvgl.h>
#include <tactility/module.h>

const struct ModuleSymbol lvgl_module_symbols[] = {
    // lvgl_module
    DEFINE_MODULE_SYMBOL(lvgl_lock),
    DEFINE_MODULE_SYMBOL(lvgl_try_lock),
    DEFINE_MODULE_SYMBOL(lvgl_unlock),
    DEFINE_MODULE_SYMBOL(lvgl_is_running),
    DEFINE_MODULE_SYMBOL(lvgl_get_ui_density),
    // lvgl_fonts
    DEFINE_MODULE_SYMBOL(lvgl_get_shared_icon_font),
    DEFINE_MODULE_SYMBOL(lvgl_get_shared_icon_font_height),
    DEFINE_MODULE_SYMBOL(lvgl_get_text_font),
    DEFINE_MODULE_SYMBOL(lvgl_get_text_font_height),
    DEFINE_MODULE_SYMBOL(lvgl_get_launcher_icon_font),
    DEFINE_MODULE_SYMBOL(lvgl_get_launcher_icon_font_height),
    DEFINE_MODULE_SYMBOL(lvgl_get_statusbar_icon_font),
    DEFINE_MODULE_SYMBOL(lvgl_get_statusbar_icon_font_height),
    // lv_event
    DEFINE_MODULE_SYMBOL(lv_event_get_code),
    DEFINE_MODULE_SYMBOL(lv_event_get_indev),
    DEFINE_MODULE_SYMBOL(lv_event_get_key),
    DEFINE_MODULE_SYMBOL(lv_event_get_param),
    DEFINE_MODULE_SYMBOL(lv_event_get_scroll_anim),
    DEFINE_MODULE_SYMBOL(lv_event_get_user_data),
    DEFINE_MODULE_SYMBOL(lv_event_get_target_obj),
    DEFINE_MODULE_SYMBOL(lv_event_get_target),
    DEFINE_MODULE_SYMBOL(lv_event_get_current_target_obj),
    DEFINE_MODULE_SYMBOL(lv_event_get_draw_task),
    DEFINE_MODULE_SYMBOL(lv_event_stop_bubbling),
    DEFINE_MODULE_SYMBOL(lv_event_get_layer),
    // lv_obj
    DEFINE_MODULE_SYMBOL(lv_color_hex),
    DEFINE_MODULE_SYMBOL(lv_color_make),
    DEFINE_MODULE_SYMBOL(lv_color_black),
    DEFINE_MODULE_SYMBOL(lv_color_white),
    DEFINE_MODULE_SYMBOL(lv_color_lighten),
    DEFINE_MODULE_SYMBOL(lv_color_darken),
    DEFINE_MODULE_SYMBOL(lv_color_hsv_to_rgb),
    DEFINE_MODULE_SYMBOL(lv_color_to_32),
    DEFINE_MODULE_SYMBOL(lv_obj_center),
    DEFINE_MODULE_SYMBOL(lv_obj_clean),
    DEFINE_MODULE_SYMBOL(lv_obj_create),
    DEFINE_MODULE_SYMBOL(lv_obj_delete),
    DEFINE_MODULE_SYMBOL(lv_obj_add_event_cb),
    DEFINE_MODULE_SYMBOL(lv_obj_add_flag),
    DEFINE_MODULE_SYMBOL(lv_obj_add_state),
    DEFINE_MODULE_SYMBOL(lv_obj_set_state),
    DEFINE_MODULE_SYMBOL(lv_obj_align),
    DEFINE_MODULE_SYMBOL(lv_obj_align_to),
    DEFINE_MODULE_SYMBOL(lv_obj_get_parent),
    DEFINE_MODULE_SYMBOL(lv_obj_get_height),
    DEFINE_MODULE_SYMBOL(lv_obj_get_width),
    DEFINE_MODULE_SYMBOL(lv_obj_get_coords),
    DEFINE_MODULE_SYMBOL(lv_obj_get_x),
    DEFINE_MODULE_SYMBOL(lv_obj_get_display),
    DEFINE_MODULE_SYMBOL(lv_obj_get_y),
    DEFINE_MODULE_SYMBOL(lv_obj_get_content_width),
    DEFINE_MODULE_SYMBOL(lv_obj_get_content_height),
    DEFINE_MODULE_SYMBOL(lv_obj_get_group),
    DEFINE_MODULE_SYMBOL(lv_obj_get_user_data),
    DEFINE_MODULE_SYMBOL(lv_obj_get_state),
    DEFINE_MODULE_SYMBOL(lv_obj_get_scroll_bottom),
    DEFINE_MODULE_SYMBOL(lv_obj_get_scroll_y),
    DEFINE_MODULE_SYMBOL(lv_obj_has_flag),
    DEFINE_MODULE_SYMBOL(lv_obj_has_flag_any),
    DEFINE_MODULE_SYMBOL(lv_obj_has_state),
    DEFINE_MODULE_SYMBOL(lv_obj_invalidate),
    DEFINE_MODULE_SYMBOL(lv_obj_is_valid),
    DEFINE_MODULE_SYMBOL(lv_obj_remove_event_cb),
    DEFINE_MODULE_SYMBOL(lv_obj_remove_flag),
    DEFINE_MODULE_SYMBOL(lv_obj_remove_state),
    DEFINE_MODULE_SYMBOL(lv_obj_set_pos),
    DEFINE_MODULE_SYMBOL(lv_obj_set_flex_align),
    DEFINE_MODULE_SYMBOL(lv_obj_set_flex_flow),
    DEFINE_MODULE_SYMBOL(lv_obj_set_flex_grow),
    DEFINE_MODULE_SYMBOL(lv_obj_set_layout),
    DEFINE_MODULE_SYMBOL(lv_obj_is_layout_positioned),
    DEFINE_MODULE_SYMBOL(lv_obj_mark_layout_as_dirty),
    DEFINE_MODULE_SYMBOL(lv_obj_get_style_layout),
    DEFINE_MODULE_SYMBOL(lv_obj_update_layout),
    DEFINE_MODULE_SYMBOL(lv_obj_set_scroll_dir),
    DEFINE_MODULE_SYMBOL(lv_obj_scroll_to_view),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_radius),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_border_width),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_border_color),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_border_opa),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_line_width),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_line_color),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_line_opa),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_line_rounded),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_opa),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_bg_color),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_bg_opa),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_bg_image_src),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_bg_image_opa),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_bg_image_recolor),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_bg_image_recolor_opa),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_margin_hor),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_margin_ver),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_margin_top),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_margin_bottom),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_margin_left),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_margin_right),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_margin_all),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_pad_all),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_pad_hor),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_pad_ver),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_pad_top),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_pad_bottom),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_pad_left),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_pad_right),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_pad_column),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_pad_row),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_border_post),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_border_side),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_text_opa),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_text_align),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_text_color),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_text_font),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_text_decor),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_text_letter_space),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_text_line_space),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_text_outline_stroke_color),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_text_outline_stroke_opa),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_text_outline_stroke_width),
    DEFINE_MODULE_SYMBOL(lv_obj_set_user_data),
    DEFINE_MODULE_SYMBOL(lv_obj_set_align),
    DEFINE_MODULE_SYMBOL(lv_obj_set_x),
    DEFINE_MODULE_SYMBOL(lv_obj_set_y),
    DEFINE_MODULE_SYMBOL(lv_obj_set_size),
    DEFINE_MODULE_SYMBOL(lv_obj_set_width),
    DEFINE_MODULE_SYMBOL(lv_obj_set_height),
    DEFINE_MODULE_SYMBOL(lv_obj_send_event),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_outline_color),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_outline_width),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_outline_pad),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_outline_opa),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_flex_cross_place),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_image_recolor_opa),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_pad_gap),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_shadow_width),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_size),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_transform_pivot_x),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_transform_pivot_y),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_transform_rotation),
    DEFINE_MODULE_SYMBOL(lv_obj_scroll_to_y),
    DEFINE_MODULE_SYMBOL(lv_obj_set_scrollbar_mode),
    DEFINE_MODULE_SYMBOL(lv_obj_get_child_count),
    DEFINE_MODULE_SYMBOL(lv_obj_get_child),
    DEFINE_MODULE_SYMBOL(lv_obj_get_index),
    DEFINE_MODULE_SYMBOL(lv_obj_remove_style_all),
    DEFINE_MODULE_SYMBOL(lv_obj_set_content_height),
    DEFINE_MODULE_SYMBOL(lv_obj_set_content_width),
    DEFINE_MODULE_SYMBOL(lv_obj_event_base),
    DEFINE_MODULE_SYMBOL(lv_obj_class_create_obj),
    DEFINE_MODULE_SYMBOL(lv_obj_class_init_obj),
    DEFINE_MODULE_SYMBOL(lv_obj_move_foreground),
    DEFINE_MODULE_SYMBOL(lv_obj_move_to_index),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_min_height),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_max_height),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_width),
    DEFINE_MODULE_SYMBOL(lv_obj_set_style_height),
    // lv_font
    DEFINE_MODULE_SYMBOL(lv_font_get_bitmap_fmt_txt),
    DEFINE_MODULE_SYMBOL(lv_font_get_default),
    DEFINE_MODULE_SYMBOL(lv_font_get_glyph_bitmap),
    DEFINE_MODULE_SYMBOL(lv_font_get_glyph_dsc),
    DEFINE_MODULE_SYMBOL(lv_font_get_glyph_dsc_fmt_txt),
    DEFINE_MODULE_SYMBOL(lv_font_get_glyph_static_bitmap),
    DEFINE_MODULE_SYMBOL(lv_font_get_glyph_width),
    DEFINE_MODULE_SYMBOL(lv_font_get_line_height),
    DEFINE_MODULE_SYMBOL(lv_font_set_kerning),
    // lv_theme
    DEFINE_MODULE_SYMBOL(lv_theme_get_color_primary),
    DEFINE_MODULE_SYMBOL(lv_theme_get_color_secondary),
    DEFINE_MODULE_SYMBOL(lv_theme_get_font_small),
    DEFINE_MODULE_SYMBOL(lv_theme_get_font_normal),
    DEFINE_MODULE_SYMBOL(lv_theme_get_font_large),
    // lv_button
    DEFINE_MODULE_SYMBOL(lv_button_create),
    // lv_buttonmatrix
    DEFINE_MODULE_SYMBOL(lv_buttonmatrix_create),
    DEFINE_MODULE_SYMBOL(lv_buttonmatrix_get_button_text),
    DEFINE_MODULE_SYMBOL(lv_buttonmatrix_get_map),
    DEFINE_MODULE_SYMBOL(lv_buttonmatrix_get_one_checked),
    DEFINE_MODULE_SYMBOL(lv_buttonmatrix_get_selected_button),
    DEFINE_MODULE_SYMBOL(lv_buttonmatrix_set_button_ctrl),
    DEFINE_MODULE_SYMBOL(lv_buttonmatrix_set_button_ctrl_all),
    DEFINE_MODULE_SYMBOL(lv_buttonmatrix_set_ctrl_map),
    DEFINE_MODULE_SYMBOL(lv_buttonmatrix_set_map),
    DEFINE_MODULE_SYMBOL(lv_buttonmatrix_set_one_checked),
    DEFINE_MODULE_SYMBOL(lv_buttonmatrix_set_button_width),
    DEFINE_MODULE_SYMBOL(lv_buttonmatrix_set_selected_button),
    DEFINE_MODULE_SYMBOL(lv_buttonmatrix_clear_button_ctrl),
    // lv_canvas
    DEFINE_MODULE_SYMBOL(lv_canvas_create),
    DEFINE_MODULE_SYMBOL(lv_canvas_fill_bg),
    DEFINE_MODULE_SYMBOL(lv_canvas_set_draw_buf),
    DEFINE_MODULE_SYMBOL(lv_canvas_set_buffer),
    DEFINE_MODULE_SYMBOL(lv_canvas_set_px),
    // lv_label
    DEFINE_MODULE_SYMBOL(lv_label_create),
    DEFINE_MODULE_SYMBOL(lv_label_cut_text),
    DEFINE_MODULE_SYMBOL(lv_label_get_long_mode),
    DEFINE_MODULE_SYMBOL(lv_label_set_long_mode),
    DEFINE_MODULE_SYMBOL(lv_label_get_text),
    DEFINE_MODULE_SYMBOL(lv_label_set_text),
    DEFINE_MODULE_SYMBOL(lv_label_set_text_fmt),
    // lv_switch
    DEFINE_MODULE_SYMBOL(lv_switch_create),
    // lv_checkbox
    DEFINE_MODULE_SYMBOL(lv_checkbox_create),
    DEFINE_MODULE_SYMBOL(lv_checkbox_set_text),
    DEFINE_MODULE_SYMBOL(lv_checkbox_get_text),
    DEFINE_MODULE_SYMBOL(lv_checkbox_set_text_static),
    // lv_bar
    DEFINE_MODULE_SYMBOL(lv_bar_create),
    DEFINE_MODULE_SYMBOL(lv_bar_get_max_value),
    DEFINE_MODULE_SYMBOL(lv_bar_get_min_value),
    DEFINE_MODULE_SYMBOL(lv_bar_get_mode),
    DEFINE_MODULE_SYMBOL(lv_bar_get_start_value),
    DEFINE_MODULE_SYMBOL(lv_bar_get_value),
    DEFINE_MODULE_SYMBOL(lv_bar_set_mode),
    DEFINE_MODULE_SYMBOL(lv_bar_set_range),
    DEFINE_MODULE_SYMBOL(lv_bar_set_start_value),
    DEFINE_MODULE_SYMBOL(lv_bar_set_value),
    DEFINE_MODULE_SYMBOL(lv_bar_is_symmetrical),
    // lv_arc
    DEFINE_MODULE_SYMBOL(lv_arc_create),
    DEFINE_MODULE_SYMBOL(lv_arc_set_start_angle),
    DEFINE_MODULE_SYMBOL(lv_arc_set_end_angle),
    DEFINE_MODULE_SYMBOL(lv_arc_set_angles),
    DEFINE_MODULE_SYMBOL(lv_arc_set_bg_start_angle),
    DEFINE_MODULE_SYMBOL(lv_arc_set_bg_end_angle),
    DEFINE_MODULE_SYMBOL(lv_arc_set_bg_angles),
    DEFINE_MODULE_SYMBOL(lv_arc_set_rotation),
    DEFINE_MODULE_SYMBOL(lv_arc_set_mode),
    DEFINE_MODULE_SYMBOL(lv_arc_set_value),
    DEFINE_MODULE_SYMBOL(lv_arc_set_range),
    DEFINE_MODULE_SYMBOL(lv_arc_set_change_rate),
    DEFINE_MODULE_SYMBOL(lv_arc_set_knob_offset),
    DEFINE_MODULE_SYMBOL(lv_arc_get_angle_start),
    DEFINE_MODULE_SYMBOL(lv_arc_get_angle_end),
    DEFINE_MODULE_SYMBOL(lv_arc_get_bg_angle_start),
    DEFINE_MODULE_SYMBOL(lv_arc_get_bg_angle_end),
    DEFINE_MODULE_SYMBOL(lv_arc_get_value),
    DEFINE_MODULE_SYMBOL(lv_arc_get_min_value),
    DEFINE_MODULE_SYMBOL(lv_arc_get_max_value),
    DEFINE_MODULE_SYMBOL(lv_arc_get_mode),
    DEFINE_MODULE_SYMBOL(lv_arc_get_rotation),
    DEFINE_MODULE_SYMBOL(lv_arc_get_knob_offset),
    DEFINE_MODULE_SYMBOL(lv_arc_align_obj_to_angle),
    DEFINE_MODULE_SYMBOL(lv_arc_rotate_obj_to_angle),
    // lv_chart
    DEFINE_MODULE_SYMBOL(lv_chart_set_div_line_count),
    DEFINE_MODULE_SYMBOL(lv_chart_set_all_values),
    DEFINE_MODULE_SYMBOL(lv_chart_create),
    DEFINE_MODULE_SYMBOL(lv_chart_set_type),
    DEFINE_MODULE_SYMBOL(lv_chart_set_next_value),
    DEFINE_MODULE_SYMBOL(lv_chart_add_series),
    DEFINE_MODULE_SYMBOL(lv_chart_set_axis_range),
    DEFINE_MODULE_SYMBOL(lv_chart_set_update_mode),
    DEFINE_MODULE_SYMBOL(lv_chart_set_point_count),
    DEFINE_MODULE_SYMBOL(lv_chart_refresh),
    // lv_dropdown
    DEFINE_MODULE_SYMBOL(lv_dropdown_create),
    DEFINE_MODULE_SYMBOL(lv_dropdown_add_option),
    DEFINE_MODULE_SYMBOL(lv_dropdown_clear_options),
    DEFINE_MODULE_SYMBOL(lv_dropdown_close),
    DEFINE_MODULE_SYMBOL(lv_dropdown_get_dir),
    DEFINE_MODULE_SYMBOL(lv_dropdown_get_list),
    DEFINE_MODULE_SYMBOL(lv_dropdown_get_option_count),
    DEFINE_MODULE_SYMBOL(lv_dropdown_get_option_index),
    DEFINE_MODULE_SYMBOL(lv_dropdown_get_options),
    DEFINE_MODULE_SYMBOL(lv_dropdown_get_selected),
    DEFINE_MODULE_SYMBOL(lv_dropdown_get_selected_str),
    DEFINE_MODULE_SYMBOL(lv_dropdown_get_selected_highlight),
    DEFINE_MODULE_SYMBOL(lv_dropdown_set_dir),
    DEFINE_MODULE_SYMBOL(lv_dropdown_set_options),
    DEFINE_MODULE_SYMBOL(lv_dropdown_set_options_static),
    DEFINE_MODULE_SYMBOL(lv_dropdown_set_selected),
    DEFINE_MODULE_SYMBOL(lv_dropdown_set_selected_highlight),
    DEFINE_MODULE_SYMBOL(lv_dropdown_set_symbol),
    DEFINE_MODULE_SYMBOL(lv_dropdown_set_text),
    DEFINE_MODULE_SYMBOL(lv_dropdown_open),
    // lv_list
    DEFINE_MODULE_SYMBOL(lv_list_create),
    DEFINE_MODULE_SYMBOL(lv_list_add_text),
    DEFINE_MODULE_SYMBOL(lv_list_add_button),
    DEFINE_MODULE_SYMBOL(lv_list_get_button_text),
    DEFINE_MODULE_SYMBOL(lv_list_set_button_text),
    // lv_keyboard
    DEFINE_MODULE_SYMBOL(lv_keyboard_create),
    DEFINE_MODULE_SYMBOL(lv_keyboard_set_textarea),
    // lv_textarea
    DEFINE_MODULE_SYMBOL(lv_textarea_create),
    DEFINE_MODULE_SYMBOL(lv_textarea_get_accepted_chars),
    DEFINE_MODULE_SYMBOL(lv_textarea_get_label),
    DEFINE_MODULE_SYMBOL(lv_textarea_get_max_length),
    DEFINE_MODULE_SYMBOL(lv_textarea_get_one_line),
    DEFINE_MODULE_SYMBOL(lv_textarea_get_text),
    DEFINE_MODULE_SYMBOL(lv_textarea_get_text_selection),
    DEFINE_MODULE_SYMBOL(lv_textarea_set_one_line),
    DEFINE_MODULE_SYMBOL(lv_textarea_set_accepted_chars),
    DEFINE_MODULE_SYMBOL(lv_textarea_set_align),
    DEFINE_MODULE_SYMBOL(lv_textarea_set_password_bullet),
    DEFINE_MODULE_SYMBOL(lv_textarea_set_password_mode),
    DEFINE_MODULE_SYMBOL(lv_textarea_set_password_show_time),
    DEFINE_MODULE_SYMBOL(lv_textarea_set_placeholder_text),
    DEFINE_MODULE_SYMBOL(lv_textarea_set_text),
    DEFINE_MODULE_SYMBOL(lv_textarea_set_text_selection),
    DEFINE_MODULE_SYMBOL(lv_textarea_set_max_length),
    DEFINE_MODULE_SYMBOL(lv_textarea_set_cursor_click_pos),
    DEFINE_MODULE_SYMBOL(lv_textarea_add_text),
    // lv_palette
    DEFINE_MODULE_SYMBOL(lv_palette_main),
    DEFINE_MODULE_SYMBOL(lv_palette_darken),
    DEFINE_MODULE_SYMBOL(lv_palette_lighten),
    // lv_display
    DEFINE_MODULE_SYMBOL(lv_display_get_default),
    DEFINE_MODULE_SYMBOL(lv_display_get_horizontal_resolution),
    DEFINE_MODULE_SYMBOL(lv_display_get_vertical_resolution),
    DEFINE_MODULE_SYMBOL(lv_display_get_physical_horizontal_resolution),
    DEFINE_MODULE_SYMBOL(lv_display_get_physical_vertical_resolution),
    DEFINE_MODULE_SYMBOL(lv_display_dpx),
    DEFINE_MODULE_SYMBOL(lv_display_get_inactive_time),
    DEFINE_MODULE_SYMBOL(lv_display_get_rotation),
    DEFINE_MODULE_SYMBOL(lv_display_set_rotation),
    DEFINE_MODULE_SYMBOL(lv_display_set_offset),
    DEFINE_MODULE_SYMBOL(lv_display_trigger_activity),
    // lv_pct
    DEFINE_MODULE_SYMBOL(lv_pct),
    DEFINE_MODULE_SYMBOL(lv_pct_to_px),
    // lv_spinbox
    DEFINE_MODULE_SYMBOL(lv_spinbox_create),
    DEFINE_MODULE_SYMBOL(lv_spinbox_decrement),
    DEFINE_MODULE_SYMBOL(lv_spinbox_get_rollover),
    DEFINE_MODULE_SYMBOL(lv_spinbox_get_step),
    DEFINE_MODULE_SYMBOL(lv_spinbox_get_value),
    DEFINE_MODULE_SYMBOL(lv_spinbox_increment),
    DEFINE_MODULE_SYMBOL(lv_spinbox_set_rollover),
    DEFINE_MODULE_SYMBOL(lv_spinbox_set_step),
    DEFINE_MODULE_SYMBOL(lv_spinbox_set_range),
    DEFINE_MODULE_SYMBOL(lv_spinbox_set_digit_format),
    DEFINE_MODULE_SYMBOL(lv_spinbox_set_digit_step_direction),
    DEFINE_MODULE_SYMBOL(lv_spinbox_set_value),
    DEFINE_MODULE_SYMBOL(lv_spinbox_set_cursor_pos),
    DEFINE_MODULE_SYMBOL(lv_spinbox_step_next),
    DEFINE_MODULE_SYMBOL(lv_spinbox_step_prev),
    // lv_indev
    DEFINE_MODULE_SYMBOL(lv_indev_get_type),
    DEFINE_MODULE_SYMBOL(lv_indev_get_point),
    DEFINE_MODULE_SYMBOL(lv_indev_get_display),
    DEFINE_MODULE_SYMBOL(lv_indev_get_key),
    DEFINE_MODULE_SYMBOL(lv_indev_get_gesture_dir),
    DEFINE_MODULE_SYMBOL(lv_indev_get_state),
    DEFINE_MODULE_SYMBOL(lv_indev_active),
    DEFINE_MODULE_SYMBOL(lv_indev_get_next),
    DEFINE_MODULE_SYMBOL(lv_indev_set_group),
    DEFINE_MODULE_SYMBOL(lv_indev_wait_release),
    // lv_timer
    DEFINE_MODULE_SYMBOL(lv_timer_handler),
    DEFINE_MODULE_SYMBOL(lv_timer_handler_run_in_period),
    DEFINE_MODULE_SYMBOL(lv_timer_periodic_handler),
    DEFINE_MODULE_SYMBOL(lv_timer_handler_set_resume_cb),
    DEFINE_MODULE_SYMBOL(lv_timer_create_basic),
    DEFINE_MODULE_SYMBOL(lv_timer_create),
    DEFINE_MODULE_SYMBOL(lv_timer_delete),
    DEFINE_MODULE_SYMBOL(lv_timer_pause),
    DEFINE_MODULE_SYMBOL(lv_timer_resume),
    DEFINE_MODULE_SYMBOL(lv_timer_set_cb),
    DEFINE_MODULE_SYMBOL(lv_timer_set_period),
    DEFINE_MODULE_SYMBOL(lv_timer_ready),
    DEFINE_MODULE_SYMBOL(lv_timer_set_repeat_count),
    DEFINE_MODULE_SYMBOL(lv_timer_set_auto_delete),
    DEFINE_MODULE_SYMBOL(lv_timer_set_user_data),
    DEFINE_MODULE_SYMBOL(lv_timer_reset),
    DEFINE_MODULE_SYMBOL(lv_timer_enable),
    DEFINE_MODULE_SYMBOL(lv_timer_get_idle),
    DEFINE_MODULE_SYMBOL(lv_timer_get_time_until_next),
    DEFINE_MODULE_SYMBOL(lv_timer_get_next),
    DEFINE_MODULE_SYMBOL(lv_timer_get_user_data),
    DEFINE_MODULE_SYMBOL(lv_timer_get_paused),
    // lvgl other
    DEFINE_MODULE_SYMBOL(lv_refr_now),
    DEFINE_MODULE_SYMBOL(lv_line_create),
    DEFINE_MODULE_SYMBOL(lv_line_set_points),
    DEFINE_MODULE_SYMBOL(lv_line_set_points_mutable),
    DEFINE_MODULE_SYMBOL(lv_tick_get),
    DEFINE_MODULE_SYMBOL(lv_tick_elaps),
    // lv_slider
    DEFINE_MODULE_SYMBOL(lv_slider_create),
    DEFINE_MODULE_SYMBOL(lv_slider_get_value),
    DEFINE_MODULE_SYMBOL(lv_slider_set_range),
    DEFINE_MODULE_SYMBOL(lv_slider_set_value),
    DEFINE_MODULE_SYMBOL(lv_slider_set_mode),
    // lv_tabview
    DEFINE_MODULE_SYMBOL(lv_tabview_add_tab),
    DEFINE_MODULE_SYMBOL(lv_tabview_create),
    DEFINE_MODULE_SYMBOL(lv_tabview_set_tab_bar_position),
    DEFINE_MODULE_SYMBOL(lv_tabview_set_tab_bar_size),
    DEFINE_MODULE_SYMBOL(lv_tabview_get_tab_active),
    DEFINE_MODULE_SYMBOL(lv_tabview_get_content),
    // lv_screen
    DEFINE_MODULE_SYMBOL(lv_scr_act),
    DEFINE_MODULE_SYMBOL(lv_screen_active),
    DEFINE_MODULE_SYMBOL(lv_layer_top),
    // lv_group
    DEFINE_MODULE_SYMBOL(lv_group_remove_obj),
    DEFINE_MODULE_SYMBOL(lv_group_focus_obj),
    DEFINE_MODULE_SYMBOL(lv_group_get_default),
    DEFINE_MODULE_SYMBOL(lv_group_add_obj),
    DEFINE_MODULE_SYMBOL(lv_group_set_default),
    DEFINE_MODULE_SYMBOL(lv_group_set_editing),
    DEFINE_MODULE_SYMBOL(lv_group_create),
    DEFINE_MODULE_SYMBOL(lv_group_delete),
    DEFINE_MODULE_SYMBOL(lv_group_get_editing),
    // lv_mem
    DEFINE_MODULE_SYMBOL(lv_free),
    DEFINE_MODULE_SYMBOL(lv_malloc),
    // lv_draw
    DEFINE_MODULE_SYMBOL(lv_draw_task_get_draw_dsc),
    DEFINE_MODULE_SYMBOL(lv_draw_task_get_label_dsc),
    DEFINE_MODULE_SYMBOL(lv_draw_task_get_fill_dsc),
    DEFINE_MODULE_SYMBOL(lv_draw_buf_create),
    // lv_image
    DEFINE_MODULE_SYMBOL(lv_image_create),
    DEFINE_MODULE_SYMBOL(lv_image_set_src),
    // lv_anim
    DEFINE_MODULE_SYMBOL(lv_anim_init),
    DEFINE_MODULE_SYMBOL(lv_anim_set_duration),
    DEFINE_MODULE_SYMBOL(lv_anim_set_exec_cb),
    DEFINE_MODULE_SYMBOL(lv_anim_set_repeat_count),
    DEFINE_MODULE_SYMBOL(lv_anim_set_values),
    DEFINE_MODULE_SYMBOL(lv_anim_set_var),
    DEFINE_MODULE_SYMBOL(lv_anim_set_path_cb),
    DEFINE_MODULE_SYMBOL(lv_anim_start),
    DEFINE_MODULE_SYMBOL(lv_anim_path_ease_in_out),
    DEFINE_MODULE_SYMBOL(lv_anim_path_linear),
    DEFINE_MODULE_SYMBOL(lv_anim_path_ease_in),
    DEFINE_MODULE_SYMBOL(lv_anim_path_ease_out),
    // lv_async
    DEFINE_MODULE_SYMBOL(lv_async_call),
    // lv_span
    DEFINE_MODULE_SYMBOL(lv_spangroup_create),
    DEFINE_MODULE_SYMBOL(lv_spangroup_set_align),
    DEFINE_MODULE_SYMBOL(lv_spangroup_set_mode),
    DEFINE_MODULE_SYMBOL(lv_spangroup_add_span),
    DEFINE_MODULE_SYMBOL(lv_spangroup_refresh),
    DEFINE_MODULE_SYMBOL(lv_span_get_style),
    DEFINE_MODULE_SYMBOL(lv_span_set_text),
    // lv_binfont
    DEFINE_MODULE_SYMBOL(lv_binfont_create),
    DEFINE_MODULE_SYMBOL(lv_binfont_destroy),
    // lv_style_gen
    DEFINE_MODULE_SYMBOL(lv_style_set_text_font),
    // lv_draw_line
    DEFINE_MODULE_SYMBOL(lv_draw_line),
    DEFINE_MODULE_SYMBOL(lv_draw_line_dsc_init),
    // lv_draw_rect
    DEFINE_MODULE_SYMBOL(lv_draw_fill),
    DEFINE_MODULE_SYMBOL(lv_draw_fill_dsc_init),
    // lv_area
    DEFINE_MODULE_SYMBOL(lv_area_get_width),
    DEFINE_MODULE_SYMBOL(lv_area_get_height),
    MODULE_SYMBOL_TERMINATOR
};