general.vendor=Guition
general.name=JC8048W550C

apps.launcherAppId=Launcher

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=OCT
hardware.spiRamSpeed=80M
hardware.esptoolFlashFreq=80M
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=5"
display.shape=rectangle
display.dpi=187

lvgl.colorDepth=16
lvgl.fontSize=18

sdkconfig.CONFIG_CODEC_DUMMY_SUPPORT=y
