@startuml
skinparam componentStyle uml1

[Tactility] as t
note right of t : to build and use graphical apps
[TactilityCore] as tcore
note right of tcore : defines, data types, logging, async, etc.

[App] as app

note right of app : App depends on the board \n projects for configuration

[app] ..> [t]
[t] ..> [tcore]

@enduml