general.vendor=CYD
general.name=8048S043C
general.incubating=false

apps.launcherAppId=Launcher

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=OCT
hardware.spiRamSpeed=80M
hardware.esptoolFlashFreq=80M
hardware.bluetooth=true

storage.userDataLocation=SD

display.size=4.3"
display.shape=rectangle
display.dpi=217

cdn.infoMessage=
cdn.warningMessage=

lvgl.theme=DefaultDark
lvgl.colorDepth=16
lvgl.fontSize=18
