#pragma once

#include "driver/spi_common.h"
#include "driver/i2c.h"
#include "driver/gpio.h"

// SPI2 - Display, SD
#define CORES3_SPI2_TRANSACTION_LIMIT CORES3_LCD_DRAW_BUFFER_SIZE

// Display
#define CORES3_LCD_HORIZONTAL_RESOLUTION 320
#define CORES3_LCD_VERTICAL_RESOLUTION 240
#define CORES3_LCD_BITS_PER_PIXEL 16
#define CORES3_LCD_DRAW_BUFFER_HEIGHT (CORES3_LCD_VERTICAL_RESOLUTION / 10)
#define CORES3_LCD_DRAW_BUFFER_SIZE (CORES3_LCD_HORIZONTAL_RESOLUTION * CORES3_LCD_DRAW_BUFFER_HEIGHT * (CORES3_LCD_BITS_PER_PIXEL / 8))

// Touch
#define CORES3_TOUCH_I2C_PORT I2C_NUM_0

// SD Card
#define CORES3_SDCARD_SPI_HOST SPI2_HOST
#define CORES3_SDCARD_PIN_CS GPIO_NUM_4
#define CORES3_SDCARD_SPI_FREQUENCY 800000U
#define CORES3_SDCARD_FORMAT_ON_MOUNT_FAILED false
#define CORES3_SDCARD_MAX_OPEN_FILES 4
#define CORES3_SDCARD_ALLOC_UNIT_SIZE (16 * 1024)
#define CORES3_SDCARD_STATUS_CHECK_ENABLED false
