name: Build Yellow Board
on: [push]
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Yellow Board
        uses: ./.github/actions/build-esp-variant
        with:
          board-name: yellowboard
          version: snapshot
          sdkconfig: sdkconfig.board.yellow_board
          arch: esp32