name: Build
on: [push]
jobs:
  Build-Yellow-Board:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Board select
        run: cp sdkconfig.board.yellow_board sdkconfig
      - name: build
        uses: espressif/esp-idf-ci-action@main
        with:
          esp_idf_version: v5.2
          target: esp32
          path: './'
  build-lilygo-t-deck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: board select
        run: cp sdkconfig.board.lilygo_tdeck sdkconfig
      - name: build
        uses: espressif/esp-idf-ci-action@main
        with:
          esp_idf_version: v5.2
          target: esp32s3
          path: './'
  build-waveshare-s3-touch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: board select
        run: cp sdkconfig.board.waveshare_s3_touch sdkconfig
      - name: build
        uses: espressif/esp-idf-ci-action@main
        with:
          esp_idf_version: v5.2
          target: esp32s3
          path: './'
  build-m5stack-core2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: board select
        run: cp sdkconfig.board.m5stack_core2 sdkconfig
      - name: build
        uses: espressif/esp-idf-ci-action@main
        with:
          esp_idf_version: v5.2
          target: esp32
          path: './'
