name: Build
on: [push]
jobs:
  Build-Yellow-Board:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Board select
        run: cp sdkconfig.board.yellow_board sdkconfig
      - name: esp32 build
        uses: espressif/esp-idf-ci-action@main
        with:
          esp_idf_version: v5.1.2
          target: esp32
          path: './'
  Build-Lilygo-T-Deck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Board select
        run: cp sdkconfig.board.lilygo_tdeck sdkconfig
      - name: esp32s3 build
        uses: espressif/esp-idf-ci-action@main
        with:
          esp_idf_version: v5.1.2
          target: esp32s3
          path: './'
  Build-PC:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
      - name: Prepare Project
        runs: cmake -S ./ -B build
      - name: Build Project
        runs: cmake --build build
