name: Build
on: [push]
jobs:
  Build-PC:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup SDL2 frameworks
        uses: BrettDong/setup-sdl2-frameworks@main
        with:
          sdl2: latest
          sdl2-ttf: none
          sdl2-image: none
          sdl2-mixer: none
          sdl2-net: none
      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
      - name: Prepare Project
        run: cmake -S ./ -B build
      - name: Build Project
        env:
          USE_SDL_WITH_NAMESPACE: true
        run: cmake --build build
