general.vendor=LilyGO
general.name=T-Display S3

apps.launcherAppId=Launcher
apps.autoStartAppId=ApWebServer

hardware.target=ESP32S3
hardware.flashSize=16MB
hardware.spiRam=true
hardware.spiRamMode=OCT
hardware.spiRamSpeed=120M
hardware.tinyUsb=true
hardware.esptoolFlashFreq=120M
hardware.bluetooth=true

storage.userDataLocation=Internal

display.size=1.9"
display.shape=rectangle
display.dpi=191

lvgl.colorDepth=16
